### ISSUE TITLE
include enough info to duplicate the test results

### ISSUE THREAD

**Issue by yehosef** [influxdata/influxdb-comparisons#1]
Please include the cluster details (CPU/disk/memory) * number machines, etc.  Also need the specific elasticsearch configuration and mappings used - not vague references

**Comment by yehosef** [comment]
I found the server config in the PDF.  Still need to see the ES config and mappings.

**Comment by gunnaraasen** [comment]
@yehosef The [configuration for ES](https://github.com/influxdata/influxdb-comparisons#elasticsearch-specific-configuration) is discussed in depth in the repo README. Out of the box defaults were used for all configuration settings not mentioned in that section. The testing code has the actual [default](https://github.com/influxdata/influxdb-comparisons/blob/master/bulk_load_es/main.go#L48) and the [aggregation](https://github.com/influxdata/influxdb-comparisons/blob/master/bulk_load_es/main.go#L68) mappings.

All of the tests were conducted on two dedicated machines running Ubuntu
16.04 LTS, with a single E5-1271v3 Xeon processor (quad-core, 8MB cache, 3.6GHz), 32GB
of PC3-12800 1600MHz DDR3 RAM, and a single 1.2TB Intel 750 NVMe SSD. For each
test, one machine served as the data load and query client, and the other ran only the
database server. Both machines were connected over a single Gigabit ethernet interface.

**Comment by yehosef** [comment]
Thanks for the reference for the mappings - I didn't see those. 

In the aggregation template you choose  "index": "no" for non-text fields.  Is that intentional? - it makes the field non-queryable - in most cases you would want that to be non-indexed like the others.

You have the refresh_interval set to 5 seconds but for a bulk import it's recommended to turn that off to speed up the import (unless you're simulating a live ingestion rate).  You presumably have the default of 5 shards and 1 replica set - which wouldn't be the best case for a single machine test. The shards gives you balancing across nodes and replicas gives you duplicates in case of failure.  In a single node test these are extra overhead.  I think if we had the mappings after the import (GET /<index>/_mapping also included in the this repo this would be more obvious and would be easier to suggest changes.

You also can set "store" to false for properties the aggregate result to save space (see https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-store.html).  You would only need store=true if you are querying against individual rows and need those fields.  If you are only doing aggregations, you don't need to store the _source or the field value, the index has the value but is only accessible via the aggregations, not as a direct query. 

You discussed the configuration - it would be better to include the elasticsearch.yml because it's still not clear what you actually used.  There are many other options to adjust besides what you mentioned.   ie, did you set bootstrap.mlockall: 'true'?  increase indices.store.throttle.max_bytes_per_sec or indices.memory.index.buffer.size?  As you pointed out, there are many options and they can have a big impact on performance.

After all this, I still expect influx to outperform ES in this test case, I just don't think the difference will be as dramatic.
