### ISSUE TITLE
Clusterd setup

### ISSUE THREAD

**Issue by git001** [influxdata/influxdb-comparisons#11]
Maybe I have overseen this topic in the README but how is the benchmark when you compare mongodb cluster with 3 or 5 instances with influxdb cluster with 3 or 5 instances .

Normally in a cloud you have more the one instanze.
What happens when one of the instances  is gone at run time (read, write, query)?

**Comment by rw** [comment]
This benchmarking suite is compatible with clusters as long as there is one endpoint URL (e.g. a master node for a db cluster).

General cluster support (e.g. round-robin connections) is TODO.
