### ISSUE TITLE
how to test query performance against Elasticsearch?

### ISSUE THREAD

**Issue by hanj4096** [influxdata/influxdb-comparisons#134]
Hi guys,
how to test query performance against Elasticsearch? like https://www.influxdata.com/blog/influxdb-markedly-elasticsearch-in-time-series-data-metrics-benchmark/ .
I failed to reproduce the test case with influxdb-comparisons and have met error like "bad time bounds", "fielddata is not ture", etc.
Can anyone help to show the details of test step?

**Comment by vlastahajek** [comment]
Hi @hanj4096,
What version of Elasticsearch do you have? If 7, the reason could be the framework was not tested and updated to ES 7 yet.

**Comment by hanj4096** [comment]
Thanks for help, Vlasta.

The version of ES in test is 6.6.0 . 
InfluxDB query test command:
./bulk_query_gen -query-type groupby  -timestamp-start 2018-01-01T00:00:00Z -timestamp-end 2018-01-02T01:00:00Z -format influx-http |./query_benchmarker_influxdb  -urls http://influxdb-server:8086

ES query test command:
./bulk_query_gen -query-type groupby  -timestamp-start 2018-01-01T00:00:00Z -timestamp-end 2018-01-02T01:00:00Z -format es-http |./query_benchmarker_es  -urls http://elasticsearch-server:9200
daemon URLs: [http://elasticsearch-server:9200]
using random seed 565409769
2019/06/06 16:37:38 Error during request: Invalid write response (status 400): {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [hostname] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"cpu","node":"a-7hFd9DRaaejFX2MNRMjg","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [hostname] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [hostname] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.","caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [hostname] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}},"status":400}

**Comment by vlastahajek** [comment]
Hi @hanj4096 ,
this is a bug, but it happens only if you use the `default` index template and the `groupby` query. 
I would suggest you to use the (preferred) `aggregation` index template when loading data, which is more suitable for the time series data, and it will be ok.

**Comment by hanj4096** [comment]
Thanks, Vlasta. Sorry for late reply.

It works, but the resulut is different with influxdata's test results. The ES is faster.
./bulk_query_gen -query-type groupby -query-interval 1m  -timestamp-start 2018-01-01T00:00:00Z -timestamp-end 2018-01-02T01:00:00Z -format es-http |./query_benchmarker_es  -urls http://elasticsearch-server:9200
......
run complete after 1000 queries with 1 workers:
Elastic mean cpu, all hosts, rand 1day by 1hour : min:     0.37ms (2717.00/sec), mean:     0.58ms (1727.09/sec), max:    6.90ms (145.00/sec), count:     1000, sum:   0.6sec 
all queries                                     : min:     0.37ms (2717.00/sec), mean:     0.58ms (1727.09/sec), max:    6.90ms (145.00/sec), count:     1000, sum:   0.6sec 
wall clock time: 0.583132sec

Details about test environment:
hardware: 28core + 256G memory
InfluxDB-1.7.4
ES-6.6.0

Details about ES test steps:
./bulk_data_gen -format "es-bulk6x" | ./bulk_load_es  -index-template aggregation -batch-size 100 -workers 10 -urls http://elasticsearch-server:9200
./bulk_query_gen -query-type groupby -query-interval 1m -timestamp-start 2018-01-01T00:00:00Z -timestamp-end 2018-01-02T01:00:00Z -format influx-http |./query_benchmarker_influxdb  -urls http://influxdb-server:8086

Hi Vlasta, could you help on it? Is there any wrong in  above test step?
