### ISSUE TITLE
Commit elasticsearch default and aggregation index templates

### ISSUE THREAD

**Issue by andyfeller** [influxdata/influxdb-comparisons#15]
Within the project readme, 2 elasticsearch index templates are mentioned for the setup and configuration, however they are not found within the repository.

> Third, we developed two Elasticsearch index templates, each of which represents a way we think people use Elasticsearch to store time-series data:
> 
> The first template, called ‘default’, stores time-series data in a way that enables fast querying, while also storing the original document data. This is closest to Elasticsearch’s default behavior and is a reasonable starting point for most users, although its on-disk size may become large.
> 
> The second template, called ‘aggregation’, indexes time-series data in a way that saves disk space by discarding the original point data. All data is stored in a compressed form inside the Lucene indexes, therefore all queries are completely accurate. But, due to an implementation detail of Elastic, the underlying point data is no longer independently addressable. For users who only conduct aggregation queries, this saves quite a bit of disk space (and improves bulk load speed) without any downsides.

In order to reproduce these benchmarks, it'd would be helpful to have the actual index templates used checked in.

**Comment by rw** [comment]
Hi @andyfeller, these templates are accessed via flags in the `bulk_load_es` program. Please let me know if that addresses your question.

**Comment by andyfeller** [comment]
Ah I [see it](https://github.com/influxdata/influxdb-comparisons/blob/master/cmd/bulk_load_es/main.go#L66) now!  Thanks @rw
