### ISSUE TITLE
Unable to execute queries using Cassandra

### ISSUE THREAD

**Issue by mccstan** [influxdata/influxdb-comparisons#17]
I'm trying to do a bencmark between Cassandra and influxDB, everything is fine with influxDB. I was able to generate and load Data to Cassandra. But i can't execute the queries.
This is what i'm getting.
`[mccstan@bmgs-soat bench-soat]$ $GOBIN/bulk_query_gen -query-type "1-host-1-hr" | $GOBIN/query_benchmarker_cassandra --url=127.0.0.1:9042 
using random seed 24982743
2017/06/07 17:17:04 invalid aggregation plan
`

Can someone help ?
Thank you !

**Comment by vlastahajek** [comment]
You have to specify the `--aggregation-plan` command line option for  
query_benchmarker_cassandra.
